### ISSUE TITLE
Segment translations not included in pyproject.toml

### ISSUE THREAD

**Issue by asongtoruin** [Transport-for-the-North/caf.core#43]
At present we have the `segment.yml` files included within `pyproject.toml`, but not the `segment_to_segment.csv` files. This means we can't use the correspondence with a `pip install`'ed `caf.core`. It's simply this section that needs modifying to also include `"seg_translations/*.csv"`:

https://github.com/Transport-for-the-North/caf.core/blob/94e8dc69f3bec8478aefbbe2e831d443f488013a/pyproject.toml#L62-L63

**Comment by asongtoruin** [comment]
@isaac-tfn this now throws an error (and a very confusing one at that) when we try to pip install:

```
ERROR: Exception:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\normits_lu\Lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\normits_lu\Lib\site-packages\pip\_internal\cli\req_command.py", line 245, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\normits_lu\Lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\normits_lu\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 76, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\normits_lu\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 534, in collect_root_requirements
    reqs = list(
           ^^^^^
  File "C:\ProgramData\Anaconda3\envs\normits_lu\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 490, in _make_requirements_from_install_req
    cand = self._make_base_candidate_from_link(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\normits_lu\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 228, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\normits_lu\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 290, in __init__
    super().__init__(
  File "C:\ProgramData\Anaconda3\envs\normits_lu\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\normits_lu\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 222, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\normits_lu\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 301, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\normits_lu\Lib\site-packages\pip\_internal\operations\prepare.py", line 525, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\normits_lu\Lib\site-packages\pip\_internal\operations\prepare.py", line 640, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\normits_lu\Lib\site-packages\pip\_internal\operations\prepare.py", line 71, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "C:\ProgramData\Anaconda3\envs\normits_lu\Lib\site-packages\pip\_internal\distributions\sdist.py", line 37, in prepare_distribution_metadata
    self.req.load_pyproject_toml()
  File "C:\ProgramData\Anaconda3\envs\normits_lu\Lib\site-packages\pip\_internal\req\req_install.py", line 516, in load_pyproject_toml
    pyproject_toml_data = load_pyproject_toml(
                          ^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\normits_lu\Lib\site-packages\pip\_internal\pyproject.py", line 64, in load_pyproject_toml
    pp_toml = tomli.loads(f.read())
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\normits_lu\Lib\site-packages\pip\_vendor\tomli\_parser.py", line 102, in loads
    pos = key_value_rule(src, pos, out, header, parse_float)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\normits_lu\Lib\site-packages\pip\_vendor\tomli\_parser.py", line 349, in key_value_rule
    raise suffixed_err(src, pos, "Cannot overwrite a value")
pip._vendor.tomli.TOMLDecodeError: Cannot overwrite a value (at line 64, column 70)
```

**Comment by isaac-tfn** [comment]
Oh that's not much fun, and may be slightly beyond me, I'll see if there's anything I've done obviously wrong in that most recent push. Have you tried anything, like uninstalling reinstalling etc? I assume you're doing that each time there's something new anyway

**Comment by asongtoruin** [comment]
Have not tried uninstalling, but also we're having the same issue on multiple machines.
